from .vectorize import VectorizeGraphicsFunctionQuib, QVectorize
from .apply_along_axis_function_quib import AlongAxisGraphicsFunctionQuib
from .axiswise_function_quib import ReductionAxisWiseGraphicsFunctionQuib

