name: Build Wheel

on: [push, pull_request]

jobs:
  build_wheel:
    name: Build Wheel
    steps:
      - uses: actions/checkout@v3

      # Used to host cibuildwheel
      - uses: actions/setup-python@v3

      - name: Build wheel
        working-directory: ./pyquibbler
        run: python -mpip wheel -w ./dist

      - uses: actions/upload-artifact@v3
        with:
          path: ./dist/*.whl
