name: Build

on: [push, pull_request]

jobs:
  build_wheel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Used to host cibuildwheel
      - uses: actions/setup-python@v3

      - name: Build wheel
        working-directory: ./pyquibbler
        run: python -mpip wheel . -w ./dist --no-deps

      - uses: actions/upload-artifact@v3
        with:
          path: ./dist/*.whl
