name: Build and Publish

on:
  push:
    branches:
      - master


jobs:
  build_wheel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine

      - name: Build wheel
        working-directory: ./pyquibbler
        run: python -mpip wheel . -w ./dist --no-deps

      - uses: actions/upload-artifact@v3
        with:
          path: ./pyquibbler/dist/*.whl
