name: Build and Publish

on:
  release:
    types: [published]

jobs:
  build_pyquibbler:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./pyquibbler
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build twine

      - name: Build wheel and sdist
        run: python -m build --wheel --sdist --outdir dist

      - uses: actions/upload-artifact@v4
        with:
          name: pyquibbler
          path: ./pyquibbler/dist/*

  build_extension:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./pyquibbler-labextension
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          python -m pip install jupyterlab==3.1 build

      - name: Install Node.js Dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install

      - name: Build the extension
        run: |
          set -eux
          python -m pip install .

          echo "Listing Jupyter Lab Extensions"
          jupyter labextension list

          echo "Running Browser Check"
          python -m jupyterlab.browser_check

          echo "Building Wheel and sdist"
          python -m build --wheel --sdist --outdir dist

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pyquibbler_labextension
          path: ./pyquibbler-labextension/dist/*

  publish:
    needs: [build_pyquibbler, build_extension]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: .

      - name: Copy to dist
        run: |
          mkdir dist
          cp -r pyquibbler/* dist/
          cp -r pyquibbler_labextension/* dist/

      - name: Check package metadata
        run: twine check dist/*

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
